### PR TITLE
fix patient duplication

### PR DESCRIPTION
**Pull request by mozzy11**

### CODE REVIEW

**Review by pmanko — APPROVED** [review]
I think the only other consideration is making sure some patient is always selected, per our discussion on slack. 

thanks @mozzy11 !!

**Comment by mozzy11** [comment]
Alright , so to consider the existing duplicate records , we can always select the first record and not throw an error ??

**Comment by pmanko** [comment]
> Alright , so to consider the existing duplicate records , we can always select the first record and not throw an error ??

Maybe log a warning and choose the first one? As long as it doesn't affect the xds-repository functionality, it won't matter, and this is a dead-end project anyway.

**Comment by mozzy11** [comment]
yeah , done. i just log a warning

**Comment by pmanko** [comment]
@mozzy11 can we bump the module version number with this fix and release a new version?

**Review by pmanko — APPROVED** [review]
💯

**Pull request merged**
